### ISSUE TITLE
What is the parse-atl package?

### ISSUE THREAD

**Issue by KevinKelbie** [bitjson/bitauth-ide#14]
What is the parse-atl package in the package.json? I had a look on github and npm but couldn't find it.

**Comment by bitjson** [comment]
Thanks for opening an issue! And sorry about that – that's a defunct package where I implemented the first version of the language parser. That code is now [part of this file](https://github.com/bitjson/bitauth-ide/blob/14d653bb02a0202484db726e859527caa75c7f2f/src/bitauth-script/parse.ts#L8). 

I [just fixed it here](https://github.com/bitjson/bitauth-ide/commit/14d653bb02a0202484db726e859527caa75c7f2f). Thanks for the heads up!

Also, if you're trying to run `bitauth-ide` locally, I wrote [some instructions here too](https://www.reddit.com/r/btc/comments/atkn9p/just_released_bitauth_ide_open_source_language/eh4cv1r/).

**Comment by emergent-reasons** [comment]
Can confirm this lets it run with the linked instructions.
